#!/usr/bin/env bash

CUSTOM_NAME=bc3miner-hiveos
CUSTOM_VERSION=0.1.1
CUSTOM_BUILD_TARGETS="GPU_NVIDIA"
CUSTOM_DESCRIPTION="BC3Miner SHA3-256T for RTX 40/50 series"

: "${CUSTOM_CONFIG_FILENAME:=/hive/miners/custom/bc3miner-hiveos/bc3miner.conf}"
: "${CUSTOM_LOG_BASENAME:=/var/log/miner/custom/bc3miner-hiveos/bc3miner}"
: "${CUSTOM_RATE_DIR:=/var/log/miner/custom/bc3miner-hiveos/rates}"

MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
